check github actions

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -12,13 +12,16 @@ jobs:
 
     steps:
     - uses: actions/checkout@v3
-    - name: C++ linters and formatters
+    - name: Check linters and formatters
       uses: cpp-linter/cpp-linter-action@v2
       env:
         GITHUB_TOKEN: ${{ github.token }}
         TRIGGERED_BY: ${{ github.event.pull_request.user.login }}
       with:
         style: file
+        thread-comments: True
+      if: steps.linter.outputs.checks-failed > 0
+        run: echo "Some files failed the linting checks!" | exit 1
     - name: Build with make
       run: | 
         cd $(python3 setup_work_dir.py -n ${{ github.event.pull_request.user.login }})
