check github actions

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -22,7 +22,7 @@ jobs:
         thread-comments: True
     - name: Check linters and format
       if: steps.linter.outputs.checks-failed > 0
-        run: echo "Some files failed the linting checks!" | exit 1
+      run: echo "Some files failed the linting checks!" | exit 1
     - name: Build with make
       run: | 
         cd $(python3 setup_work_dir.py -n ${{ github.event.pull_request.user.login }})
